name: AWS CloudFormation Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: AWS Configure
        run: aws configure set aws_access_key_id ${{ secrets.VELLOTH_DEV_AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.VELLOTH_DEV_AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.VELLOTH_DEV_AWS_DEFAULT_REGION }}

      - name: Validate CloudFormation Template
        run: aws cloudformation validate-template --template-body file://mycloudformation/AWS-Role.yaml

      - name: Create/Update CloudFormation Stack
        run: |
          aws cloudformation deploy --template-file /mycloudformation/AWS-Role.yaml --stack-name mystack --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
