name: AWS CloudFormation Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    env:
      REGION: "us-west-1"  # Set your default region here
      Environment: "dev"  # Set your default environment here
      Application: "pnc"  # Set your default project name here
      Project: "atlas"


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: AWS Configure
        run: aws configure set aws_access_key_id ${{ secrets.VELLOTH_DEV_AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.VELLOTH_DEV_AWS_SECRET_ACCESS_KEY }} && aws configure set default.region $REGION
      - name: check pwd
        run: ls -la
      - name: Create Artifact
        run: |
          pwd
          ls -la
          zip -rq templates.zip templates
          pwd
          ls -la

      - name: Create/Update CloudFormation Stack
        run: |
          aws cloudformation deploy --template-file /home/runner/work/mycloudformation/mycloudformation/templates/AWS-Role.yaml --stack-name $Project-$Application-$Environment --parameter-overrides --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --region $REGION
